### ISSUE TITLE
Implementar relación entre Pedido y Cliente

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g4_sf#17]
### Implementar relación `ManyToOne` entre `Pedido` y `Cliente`

* **Descripción**:
  1. Añadir la relación `ManyToOne` entre `Pedido` y `Cliente`.
  2. Eliminar los constructores de la clase `Pedido`.
  3. Eliminar anotaciones `@Table` y `@Column` innecesarias o redundantes.
  4. Asegurarse de que la relación esté bien mapeada y que la base de datos refleje correctamente la relación.
* **Pull Request**:
  * Adjuntar una imagen del resultado del diagrama de base de datos.

**Comment by mmdohmen** [comment]
relacion commiteada ...
como no tenemos entidad Cliente hice la relacion con la entidad usuario ...
adjunto imagen de la tabla Pedidos donde se puede ver la fk_usuario ...
![issue 17](https://github.com/ahumadamob/2024_gc_p3_g4_sf/assets/83716941/6968b0e9-dd5a-4d60-a39a-f45bffbb120e)
