### ISSUE TITLE
Persistencia de la entidad Restaurante

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g4_sf#33]
**Descripción:**

* Crear los archivos `RestauranteRepository`, `IRestauranteService`, `RestauranteServiceImpl`, y `RestauranteController`.
  
* Implementar en el servicio los métodos `getAll`, `getById`, `save`, `delete`, y `exists`.
  
* Crear endpoints en el controlador para llamadas `get`, `post`, `put`, y `delete`.
  
* Adjuntar capturas de todas las llamadas a los métodos a través de PostMan en el pull request.

**Interfase del servicio:**
  
      public interface IRestauranteService {
        List<Restaurante> getAll();
        Restaurante getById(Long id);
        Restaurante save(Restaurante restaurante);
        void delete(Long id);
        boolean exists(Long id);
      }
  
  **URLs de los endpoints:**
  
* `GET /restaurante`
  
* `GET /restaurante/{id}`
  
* `POST /restaurante`
  
* `PUT /restaurante/{id}`
  
* `DELETE /restaurante/{id}`

**Comment by ahumadamob** [comment]
Falta adjuntar las capturas de pantalla con las evidencias

**Comment by LucasDevincenti** [comment]
![image](https://github.com/ahumadamob/2024_gc_p3_g4_sf/assets/138263895/c65b01cd-4433-4139-a35b-34b314f2a5aa)
![image](https://github.com/ahumadamob/2024_gc_p3_g4_sf/assets/138263895/c3d4addb-1c0f-49dc-b9b9-8e49a9f30a69)
![image](https://github.com/ahumadamob/2024_gc_p3_g4_sf/assets/138263895/bdf8e4b5-8525-48a8-bf5d-614d05f1b8bf)
![image](https://github.com/ahumadamob/2024_gc_p3_g4_sf/assets/138263895/990e10d7-d530-46de-8520-4ed2db346eb9)
![image](https://github.com/ahumadamob/2024_gc_p3_g4_sf/assets/138263895/d172dd5f-c195-4ef4-ad62-8234cf3acb42)

**Comment by LucasDevincenti** [comment]
![image](https://github.com/ahumadamob/2024_gc_p3_g4_sf/assets/138263895/ebb7e422-b598-422e-b84c-711dcd92fba1)
![image](https://github.com/ahumadamob/2024_gc_p3_g4_sf/assets/138263895/2742dd3a-3c1b-444f-9b65-0e06e36ec1f0)
![image](https://github.com/ahumadamob/2024_gc_p3_g4_sf/assets/138263895/fcb0a492-218e-47cc-a3b2-0f6847c242c6)
![image](https://github.com/ahumadamob/2024_gc_p3_g4_sf/assets/138263895/23bee7df-3327-4d41-ba12-05500f813a8a)
![image](https://github.com/ahumadamob/2024_gc_p3_g4_sf/assets/138263895/8adf3232-94f5-442f-afdb-4a4bc7383957)

**Comment by LucasDevincenti** [comment]
no logro hacer que funcione el delete

**Comment by LucasDevincenti** [comment]
![image](https://github.com/ahumadamob/2024_gc_p3_g4_sf/assets/138263895/fc42c2b4-bf9d-4ea2-b10e-b1885aa5fa43)
