### ISSUE TITLE
Persistencia de la entidad Usuario

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g4_sf#34]
**Descripción:**

* Crear los archivos `UsuarioRepository`, `IUsuarioService`, `UsuarioServiceImpl`, y `UsuarioController`.
  
* Implementar en el servicio los métodos `getAll`, `getById`, `save`, `delete`, y `exists`.
  
* Crear endpoints en el controlador para llamadas `get`, `post`, `put`, y `delete`.
  
* Adjuntar capturas de todas las llamadas a los métodos a través de PostMan en el pull request.

**Interfase del servicio:**
  
      public interface IUsuarioService {
        List<Usuario> getAll();
        Usuario getById(Long id);
        Usuario save(Usuario usuario);
        void delete(Long id);
        boolean exists(Long id);
      }
  
  **URLs de los endpoints:**
  
* `GET /usuario`
  
* `GET /usuario/{id}`
  
* `POST /usuario`
  
* `PUT /usuario/{id}`
  
* `DELETE /usuario/{id}`

**Comment by Leonel-18** [comment]
![Eliminado](https://github.com/ahumadamob/2024_gc_p3_g4_sf/assets/96972218/454a95c4-0f9b-4494-bb64-fa8656b42713)
![GET ALL](https://github.com/ahumadamob/2024_gc_p3_g4_sf/assets/96972218/a0fd94c9-b7e6-4af4-b78a-f875bdb7ca05)
![Get ID](https://github.com/ahumadamob/2024_gc_p3_g4_sf/assets/96972218/3cc28c97-2ac6-440a-a33a-4603ac648d2b)
![MYSQL Registros](https://github.com/ahumadamob/2024_gc_p3_g4_sf/assets/96972218/5991c724-253b-4f45-974b-48f55ed818c7)
![POST](https://github.com/ahumadamob/2024_gc_p3_g4_sf/assets/96972218/c2dc1a56-9fa4-4559-ab8d-2ba9a400b0b7)
![PUT](https://github.com/ahumadamob/2024_gc_p3_g4_sf/assets/96972218/1eccac8f-fdf4-47c8-9163-dc823b401544)

**Comment by Leonel-18** [comment]
Profe el de eliminar no lo pude mostrar, pero basicamente borra el id 7, ahora le mando una foto que si creo un nuevo usuario, sale con id 7, porque bueno el 6 ya fue ocupado / borrado

![Prueba](https://github.com/ahumadamob/2024_gc_p3_g4_sf/assets/96972218/4a03bc3b-2a1e-4e49-8154-f32185770073)
