### ISSUE TITLE
Fix Master

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g4_sf#43]

**Comment by Leonel-18** [comment]
Fix - Master completado:

![image](https://github.com/user-attachments/assets/5e512e03-695f-4324-876f-eae1cb9a7380)

![image](https://github.com/user-attachments/assets/d9f7ff80-1f5c-4243-845d-6a03319c8a99)

No hay ningun error, probe un endpoint de Restaurant (controlador que tiraba errores) y ahora funciona.

![image](https://github.com/user-attachments/assets/32b093d8-0c6d-45b0-8cfe-adaedaac522c)
