### ISSUE TITLE
Persistencia completa de la Entidad Restaurante

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g4_sf#48]

**Comment by ahumadamob** [comment]
No puedo corregirte, no sé quien es. Por favor, complete su nombre completo en el perfil de gitHub

**Comment by Nacho200031** [comment]
Profe disculpe,soy Ignacio pujado,ya cambié el nombre desde mi perfíl,solo que el nombre NACHO200031 sigue apareciendo,si visualiza mi perfil aparece mi nombre completo
